name: ${project.artifactId}
main: ${project.groupId}.DwDHelmet
version: ${project.version}
description: ${project.artifactId} replaces your head with almost any block you want.
author: DwDMadMac

commands:
    helmet:
        usage: /<command> [player]
        description: Set your/a players custom helmet that is in your hand.

permissions:
    command.helmet:
        description: Gives a player permission to set a custom helmet with an item in your hand.
        default: op
    command.helmet.exempt:
        description: Excempts a player from having their helmet placed by others.
        default: op
    command.helmet.others:
        description: Gives a player permission to set a custom helmet with an item in your hand on other players.
        default: op