name: ${project.artifactId}
main: ${project.groupId}.Main
version: ${project.version}
description: ${project.artifactId} Bukkit Plugin
author: DwDMadMac

commands:
    helmet:
        usage: /<command> [player]
        description: Set your/a players custom helmet that is in your hand.

permissions:
    command.helmet:
        description: Gives a player permission to set a custom helmet with an item in your hand.
        default: op